### PR TITLE
feat(plugin): update gradle-netflixoss-project-plugin to 8.0.0

### PR DESCRIPTION
**Pull request by Aloren**
Gradle 5.4 is required now

### CODE REVIEW

**Comment by Aloren** [comment]
@marchello2000 FYI

**Comment by marchello2000** [comment]
Thre are still a few projects that use gradle <5.4, will you push this change through to all downstream projects?

**Comment by Aloren** [comment]
Should I upgrade gradle version in these projects prior to merging this PR?

**Comment by marchello2000** [comment]
@cfieber has more expertise here - what do you think? or we can update the gradle version on those projects. Actually, i think it just might be `swabbie` that's lagging behind on 5.3...

**Comment by Aloren** [comment]
Thanks @marchello2000 @cfieber !

**Pull request closed without merging**
