### PR TITLE
fix(publish): Make publish call synchronous

### PR DESCRIPTION
**Pull request by ezimanyi**
The Bintray API provides both a synchronous and an asynchronous version of their publish API. We're currently using the asynchronous version, and returning success immediately; this is sometimes causing downstream steps in our build and validate pipleline to fail because they start before the package has actually be published. Change the publish call to be synchronous, so that Gradle task only completes when the publish has completed, and later steps can rely on the existence of the package.

### CODE REVIEW

**Comment by ezimanyi** [comment]
Bintray documentation is here: https://bintray.com/docs/api/#_publish_discard_uploaded_content

**Comment by ezimanyi** [comment]
@spinnaker/netflix-reviewers : Any concerns with changing the call to publish to Bintray to be synchronous, so we can rely on the publish being completed when we move on to the next build step?

**Comment by ewiseblatt** [comment]
Could we instead do something to poll for the packages?

**Comment by ezimanyi** [comment]
@ewiseblatt : You mean poll for the packages in the success handler of the publish call here, or poll in any downstream build step that relies on the existence of a package?

**Comment by ewiseblatt** [comment]
As a precondition before executing the hal deploy apply -- emitted by the validation script

**Comment by ewiseblatt** [comment]
Or since this isnt that common, you could have the validator look at the installer output for signs of this error, then retry rather than fail. I'm pretty sure there is logic in there already that looks for bintray errors to count them as causes for failure.

**Comment by ezimanyi** [comment]
We could, though we'd also have to do the same polling in other downstream steps (ex: I've seen `BuildComponentImages` fail for the same reason).    This also isn't strictly limited to our test cases---we publish the new BOM immediately after sending out the asynchronous request to publish packages, so an end-user who does `hal deploy apply` pointing at `master-latest-unvalidated` at the wrong time will also get this error.  (Granted, it's a reasonably small window of a few minutes, but is a race condition nonetheless.)

So if we don't want to make this synchronous, we probably need to add a blocking step to `BuildPrimaryArtifacts` to do the polling between when we publish the packages and when we publish the BOM.  I'm just not sure I see why polling would be better than using Bintray's exposed API for this.

**Comment by ewiseblatt** [comment]
There is already logic in validate_bom__deploy for this. It either no longer works or you are looking at a different scenario. Have a look there and see if that might help.

**Comment by ewiseblatt** [comment]
Perhaps add another parameter to gradle to ask synchronous?
The reason I dont want to force blocking is that netflix doesnt use those packages at all since they rebuild their own. So dont add overhead to their builds for something they dont use. They only publish them as a community service.

**Comment by ezimanyi** [comment]
Added a parameter for how long to wait for a synchronous publish, defaulting to 0 which means asynchronous (the current behavior)

**Comment by ezimanyi** [comment]
Seems like upgrading gradle-netflixoss-project-plugin from 5.1.1-rc.1 to 5.1.1 fixes it, so I'll apply that

**Pull request merged**
