### PR TITLE
chore(build): request review from oss-approvers instead of release author

### PR DESCRIPTION
**Pull request by jonsie**

### CODE REVIEW

**Comment by ezimanyi** [comment]
@jonsie : Curious about the motivation for this change?  It used to be when I bumped kork, I'd get an email for each repo so I could make sure it properly merged into each repo myself, and figure out the issue if it didn't.  Now frequently I get back to my email to find ~12 email threads that kork was auto-bumped in all repos (and usually they're already merged by when I get back so I just delete the emails).  Obviously I can try to filter these, but I do wonder whether it makes sense to email this out to everyone so often...before by emailing the person who cut the kork release it sort of reinforced that whoever cut the kork release should watch to make sure everything merged properly, whereas now there's less of that individual reponsibility.  Anyway just my $0.02, 🤷‍♂ maybe others are already filtering all their github email, but I'm still trying to hold out on needing to do that...

**Comment by jonsie** [comment]
@ezimanyi Good question, and sorry I didn't provide context in the PR comments.  Basically, in the migration from TravisCI to Github Actions I added the ability for a user to push up a tag (instead of needing to cut a release by hand) and then the action would generate the release with the correct release notes.  The issue there is the user is a bot user, for example -- 

https://github.com/spinnaker/kork/releases/tag/v7.28.0

After a quick chat with some colleagues we thought it would make sense to just ping oss-approvers on those changes.  I like this feedback though, let me see if I can find a better way.

**Comment by ezimanyi** [comment]
@jonsie : Thanks for the details!  Yeah, pushing up a tag does seem useful, and I can see why then we can't expect the bot to review the PR.

Maybe an ideal solution would be to ping oss-approvers if the PR isn't auto-merged within some amount of time (likely because the tests failed) which would reduce the noise of all the ones that get auto-merged?  Though that probably isn't easy to set up, so maybe not worth the effort.

Either way, for now I think I have a filter so these skip my inbox, so not an urgent issue, but would be great if there was some way to only ping on ones that do need attention.

**Comment by ttomsu** [comment]
+1 to trying to reduce email noise. It's been 7 days and I've seen a few releases cut and automerged that send a flurry of emails. It would be nice if we could still have that individual responsibility - is there a way to track back to who pushed the tag that kicked off the kork build?

**Comment by plumpy** [comment]
@ezimanyi @ttomsu This should be fixed now. We no longer set any reviewer on autobump PRs... then we [added a step to our mergify config so that if an autobump PR build fails it adds the `oss-approvers` reviewer](https://github.com/spinnaker/orca/pull/3580) at that point instead.

**Pull request merged**
