### PR TITLE
chore(deck): add yarn modules call before yarn build

### PR DESCRIPTION
**Pull request by link108**

### CODE REVIEW

**Comment by dbyron-sf** [comment]
Have a link to a failing deck build (or something) to look at to motivate this?

**Comment by dbyron-sf** [comment]
Plus also we may be in a bit of a circular struggle where the tests won't pass here until we have jars for some version of spinnaker published at nexus...

**Comment by link108** [comment]
@dbyron-sf should have added some context 😅  
failing deck build: https://console.cloud.google.com/cloud-build/builds;region=global/03a1c652-99ed-43f2-8377-cf708298a1ca;step=2?project=spinnaker-community

Link to slack thread with some disucssion: https://spinnakerteam.slack.com/archives/CDEGJS7B4/p1623287830009800

**Comment by dbyron-sf** [comment]
Thanks for that @link108 .  So, is there (an idea of) a corresponding deck PR that calls this new `yarnModules` task ... or is it better to add some dependency to a task that's already being invoked?

**Review by dbyron-sf — APPROVED** [review]

**Comment by link108** [comment]
Ended up going with the latter, adding `yarnModules` to the build task

**Comment by deverton** [comment]
I think this *might* have broken plugin builds that extend Deck. I've got an existing plugin that builds with 8.12.0 (i.e. before this change) but from 8.13.0 and up I get a build failure about "yarn modules" not being found.

**Comment by barcaxxx** [comment]
As @deverton said, this for sure breaks plugin development for deck. Steps to recreate: `pf4jStagePlugin`, upgrade spinnakerGradleVersion to 8.13.0+ have following effect:
```
* What went wrong:
Execution failed for task ':random-wait-deck:yarnModules'.
> Process 'command 'yarn'' finished with non-zero exit value 1

```

**Comment by vigneshm** [comment]
@link108, when you originally made this fix were you seeing failures in deck build or plugin build? `SpinnakerUIExtensionPlugin.kt` looks to be used only during plugin builds, so I'm wondering how this change fixed your issue.

**Comment by mattgogerly** [comment]
> 

Modules is a script used in the main Deck build, I don't think it has any relevance to plugin builds. Can confirm the workaround of adding a dummy modules script in plugins works though.

@link108 Is this extension used in the Deck build? I thought this was just for plugins.

**Pull request merged**
